name: samba2
services:
  test-samba-share:
    volumes:
      - ./smb.conf:/etc/samba/smb.conf
    ports:
      - 139:139
      - 137:137/udp
      - 138:138/udp
      - 445:445
    image: scitotec/test-samba-share
    command: -p -u 'frankframework;pass_123' 
       -s 'home;/tmp/shares/home;yes;no;yes;frankframework'
