name: Build and Publish Oracle Database XE

on:
  # Manually trigger the workflow with input parameters
  workflow_dispatch:
    inputs:
      oracle_version:
        description: 'Oracle Database version (e.g., 21.3.0)'
        required: true
        default: '21.3.0'
        type: string
  # Automatically run on push to main branch (optional)
  # push:
  #   branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone Oracle Docker Images Repository
        run: |
          git clone https://github.com/oracle/docker-images.git
          cd docker-images
          ls -la OracleDatabase/SingleInstance/dockerfiles

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Oracle Database XE Image
        run: |
          cd docker-images/OracleDatabase/SingleInstance/dockerfiles
          ./buildContainerImage.sh -v ${{ github.event.inputs.oracle_version }} -x
          docker images

      - name: Tag and Push Image to GitHub Container Registry
        run: |
          # Tag the image for GHCR
          docker tag oracle/database:${{ github.event.inputs.oracle_version }}-xe ghcr.io/${{ github.repository_owner }}/oracle/database:${{ github.event.inputs.oracle_version }}-xe
          
          # Push to GHCR
          docker push ghcr.io/${{ github.repository_owner }}/oracle/database:${{ github.event.inputs.oracle_version }}-xe
